/**
 * Kenya → United States Green Specialty Coffee Compliance Rules
 * Seed data for AATOS compliance module
 * 
 * Generated: 2026-08-06
 * Source: COMPLIANCE_SOURCE_MATRIX.md v1.0
 * Scope: KE → US, unroasted green coffee (Coffea arabica)
 */

export interface ComplianceRuleSeed {
  originCountry: string;
  destinationCountry: string;
  productCategoryId: string | null;
  requirementType: 'document' | 'inspection' | 'laboratory_test' | 'certification' | 'registration' | 'label' | 'permit' | 'fee' | 'tax';
  requirement: string;
  description: string;
  responsibleParty: string;
  issuingAuthority: string | null;
  estimatedTimeDays: number | null;
  estimatedCostUsd: number | null;
  validityPeriod: string | null;
  verificationMethod: string | null;
  sourceUrl: string | null;
  sourceName: string | null;
  ruleStatus: string;
  ruleVersion: number;
}

export const kenyaUsGreenCoffeeRules: ComplianceRuleSeed[] = [
  // === KENYAN EXPORT REQUIREMENTS ===
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'certification',
    requirement: 'Phytosanitary Certificate from KEPHIS',
    description: 'KEPHIS inspector examines consignment at production location or export packhouse. Certificate confirms freedom from quarantine pests and compliance with U.S. phytosanitary requirements. Required for all green coffee exports.',
    responsibleParty: 'exporter',
    issuingAuthority: 'KEPHIS (Kenya Plant Health Inspectorate Service)',
    estimatedTimeDays: 5,
    estimatedCostUsd: 100,
    validityPeriod: 'single_shipment',
    verificationMethod: 'Visual inspection of original certificate; KEPHIS verification via reference number',
    sourceUrl: 'https://kephis.org/services/phytosanitary-services/',
    sourceName: 'KEPHIS Official Website',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'permit',
    requirement: 'Valid Coffee Export License from AFA Coffee Directorate',
    description: 'All coffee exporters must be licensed by the Agriculture and Food Authority. License confirms registration and compliance with coffee industry regulations. Annual renewal required.',
    responsibleParty: 'exporter',
    issuingAuthority: 'AFA — Coffee Directorate',
    estimatedTimeDays: 21,
    estimatedCostUsd: 350,
    validityPeriod: '1_year',
    verificationMethod: 'License number verification with AFA',
    sourceUrl: 'http://afa.go.ke/coffee-directorate/',
    sourceName: 'Agriculture and Food Authority — Coffee Directorate',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'AGOA Preferential Certificate of Origin',
    description: 'Required to claim duty-free entry under African Growth and Opportunity Act (AGOA). Must be issued by designated authority (KRA or authorized chamber) and accompany shipment.',
    responsibleParty: 'exporter',
    issuingAuthority: 'Kenya Revenue Authority or designated chamber',
    estimatedTimeDays: 2,
    estimatedCostUsd: 37.5,
    validityPeriod: 'single_shipment',
    verificationMethod: 'AGOA eligibility verification via USTR website',
    sourceUrl: 'https://agoa.info/about-agoa.html',
    sourceName: 'AGOA.info / USTR',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'Kenya Revenue Authority Export Declaration',
    description: 'Mandatory customs export documentation. Includes commercial invoice, packing list, and export permit details. Filed through KRA iTax system or authorized agent.',
    responsibleParty: 'exporter',
    issuingAuthority: 'KRA (Kenya Revenue Authority)',
    estimatedTimeDays: 2,
    estimatedCostUsd: 50,
    validityPeriod: 'single_shipment',
    verificationMethod: 'KRA system reference number',
    sourceUrl: 'https://kra.go.ke/business/exporting-goods',
    sourceName: 'Kenya Revenue Authority',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'inspection',
    requirement: 'Coffee Quality Grading and Inspection Certificate',
    description: 'Green coffee must be graded according to Kenyan standards (AA, AB, PB, C, E, TT, T, MH/ML). Quality certification may be required depending on buyer specifications. Performed by AFA-licensed graders or licensed private cuppers.',
    responsibleParty: 'exporter',
    issuingAuthority: 'AFA Coffee Directorate or licensed cupper',
    estimatedTimeDays: 3,
    estimatedCostUsd: 200,
    validityPeriod: 'single_lot',
    verificationMethod: 'Grading certificate review; AFA license verification of grader',
    sourceUrl: 'http://afa.go.ke/coffee-directorate/',
    sourceName: 'AFA — Coffee Directorate',
    ruleStatus: 'active',
    ruleVersion: 1,
  },

  // === U.S. IMPORT REQUIREMENTS ===
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'registration',
    requirement: 'FDA Prior Notice Submission',
    description: 'FDA requires advance notification of all food imports. Must be submitted electronically through FDA Prior Notice System Interface (PNSI) or Customs ABI system. Includes manufacturer, shipper, product details, anticipated arrival. Must be submitted before arrival at U.S. port.',
    responsibleParty: 'importer',
    issuingAuthority: 'FDA',
    estimatedTimeDays: 0,
    estimatedCostUsd: 50,
    validityPeriod: 'single_shipment',
    verificationMethod: 'FDA PNSI confirmation number',
    sourceUrl: 'https://www.fda.gov/food/importing-food-products-united-states/prior-notice-imported-foods-system',
    sourceName: 'U.S. Food and Drug Administration',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'registration',
    requirement: 'Foreign Supplier Verification Program (FSVP) Compliance',
    description: 'Under FSMA, U.S. importers must verify foreign suppliers produce food in compliance with U.S. standards. Requires documented hazard analysis, supplier verification activities, and corrective actions. Applies to green coffee as a raw agricultural commodity.',
    responsibleParty: 'importer',
    issuingAuthority: 'FDA',
    estimatedTimeDays: null,
    estimatedCostUsd: 5000,
    validityPeriod: 'ongoing_annual',
    verificationMethod: 'FSVP documentation review; FDA inspection',
    sourceUrl: 'https://www.fda.gov/food/importing-food-products-united-states/foreign-supplier-verification-programs-fsma',
    sourceName: 'FDA — Food Safety Modernization Act',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'CBP Customs Entry with HTS Classification',
    description: 'All imports require customs entry. Green coffee HTS code: 0901.11.00 (Coffee, not roasted, not decaffeinated). Entry filed via CBP ACE system or through licensed customs broker. Must include commercial invoice, packing list, bill of lading, and other supporting documents.',
    responsibleParty: 'importer',
    issuingAuthority: 'CBP (Customs and Border Protection)',
    estimatedTimeDays: 3,
    estimatedCostUsd: 200,
    validityPeriod: 'single_entry',
    verificationMethod: 'CBP entry number and ACE system record',
    sourceUrl: 'https://www.cbp.gov/trade/professional-entry',
    sourceName: 'U.S. Customs and Border Protection',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'tax',
    requirement: 'AGOA Duty-Free Tariff Treatment',
    description: 'Green coffee (HTS 0901.11.00) from Kenya enters duty-free under AGOA if accompanied by valid Certificate of Origin. Without AGOA certificate, standard duty rates apply (check current HTS rates).',
    responsibleParty: 'importer',
    issuingAuthority: 'CBP',
    estimatedTimeDays: 0,
    estimatedCostUsd: 0,
    validityPeriod: 'per_shipment',
    verificationMethod: 'CBP duty determination on entry',
    sourceUrl: 'https://hts.usitc.gov/',
    sourceName: 'Harmonized Tariff Schedule of the United States',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'inspection',
    requirement: 'USDA APHIS Phytosanitary Inspection at Port of Entry',
    description: 'Green coffee subject to USDA APHIS inspection at first U.S. port of entry. Must present valid Kenyan phytosanitary certificate. Coffee must be free from soil, plant debris, and quarantine pests. May be subject to physical inspection, sampling, or treatment (fumigation).',
    responsibleParty: 'importer',
    issuingAuthority: 'USDA APHIS',
    estimatedTimeDays: 2,
    estimatedCostUsd: 0,
    validityPeriod: 'single_shipment',
    verificationMethod: 'APHIS inspection report or release',
    sourceUrl: 'https://www.aphis.usda.gov/aphis/ourfocus/planthealth/import-information',
    sourceName: 'USDA Animal and Plant Health Inspection Service',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'inspection',
    requirement: 'FDA Inspection and Sampling (if selected)',
    description: 'FDA may inspect, sample, and test imported coffee for pesticide residues, mycotoxins (ochratoxin A, aflatoxin), heavy metals, and filth. If sampled, laboratory analysis may take 2-10 business days. Green coffee lower risk than roasted but not exempt.',
    responsibleParty: 'importer',
    issuingAuthority: 'FDA',
    estimatedTimeDays: 6,
    estimatedCostUsd: 0,
    validityPeriod: 'per_shipment_if_sampled',
    verificationMethod: 'FDA Notice of Action (release, detention, or refusal)',
    sourceUrl: 'https://www.fda.gov/food/importing-food-products-united-states/imported-food-safety',
    sourceName: 'FDA — Imported Food Safety',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'registration',
    requirement: 'Valid Importer of Record (IOR) Status',
    description: 'Importer must have valid IRS Employer Identification Number (EIN) and be established as importer of record with CBP. Required for all commercial imports.',
    responsibleParty: 'importer',
    issuingAuthority: 'IRS / CBP',
    estimatedTimeDays: null,
    estimatedCostUsd: 0,
    validityPeriod: 'ongoing',
    verificationMethod: 'CBP importer account',
    sourceUrl: 'https://www.cbp.gov/trade/professional-entry',
    sourceName: 'U.S. Customs and Border Protection',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'permit',
    requirement: 'State-Level Agricultural Import Permits (if applicable)',
    description: 'Some destination states (e.g., California, Hawaii) may have additional agricultural import requirements or quarantine regulations. Coffee is generally exempt but verification recommended.',
    responsibleParty: 'importer',
    issuingAuthority: 'State Department of Agriculture',
    estimatedTimeDays: null,
    estimatedCostUsd: null,
    validityPeriod: 'varies',
    verificationMethod: 'State permit documentation',
    sourceUrl: null,
    sourceName: 'Varies by U.S. state',
    ruleStatus: 'active',
    ruleVersion: 1,
  },

  // === COMMERCIAL DOCUMENTATION ===
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'Commercial Invoice',
    description: 'Must include seller/buyer full legal details, product description (Coffea arabica, green, unroasted), HS code 0901.11.00, quantity in kg, unit price, total value, Incoterms 2020, payment terms, country of origin (Kenya).',
    responsibleParty: 'exporter',
    issuingAuthority: null,
    estimatedTimeDays: 0,
    estimatedCostUsd: 0,
    validityPeriod: 'single_shipment',
    verificationMethod: 'Document review and cross-check with packing list',
    sourceUrl: null,
    sourceName: 'International trade standard (ICC Incoterms)',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'Packing List',
    description: 'Must match commercial invoice. Include number of bags, type of bags (jute/gunny), gross weight, net weight, bag markings, lot numbers, and container numbers (if FCL).',
    responsibleParty: 'exporter',
    issuingAuthority: null,
    estimatedTimeDays: 0,
    estimatedCostUsd: 0,
    validityPeriod: 'single_shipment',
    verificationMethod: 'Document review against physical shipment',
    sourceUrl: null,
    sourceName: 'International trade standard',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'Bill of Lading or Air Waybill',
    description: 'Ocean bill of lading (original or telex release) or air waybill evidencing contract of carriage. Must be clean, consigned correctly, and match other documents. For coffee, typically FCL or LCL sea freight.',
    responsibleParty: 'carrier',
    issuingAuthority: 'Shipping line or airline',
    estimatedTimeDays: 0,
    estimatedCostUsd: 0,
    validityPeriod: 'single_shipment',
    verificationMethod: 'Document review; carrier booking confirmation',
    sourceUrl: null,
    sourceName: 'International trade standard',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
  {
    originCountry: 'KE',
    destinationCountry: 'US',
    productCategoryId: 'green-coffee',
    requirementType: 'document',
    requirement: 'Certificate of Analysis (if required by buyer)',
    description: 'Third-party laboratory analysis may include: moisture content (max 12%), defect count per 300g, cupping score (specialty grade 80+), water activity, pesticide residues (EU MRL or U.S. EPA tolerance), mycotoxin screening (ochratoxin A, aflatoxin). Buyer-dependent requirement.',
    responsibleParty: 'exporter',
    issuingAuthority: 'Third-party laboratory (e.g., SGS, Bureau Veritas, local accredited lab)',
    estimatedTimeDays: 5,
    estimatedCostUsd: 600,
    validityPeriod: 'single_lot',
    verificationMethod: 'Laboratory report review; accreditation check of lab',
    sourceUrl: null,
    sourceName: 'Industry standard / buyer requirement',
    ruleStatus: 'active',
    ruleVersion: 1,
  },
];

export const ruleSummary = {
  totalRules: kenyaUsGreenCoffeeRules.length,
  byType: kenyaUsGreenCoffeeRules.reduce((acc, rule) => {
    acc[rule.requirementType] = (acc[rule.requirementType] || 0) + 1;
    return acc;
  }, {} as Record<string, number>),
  byParty: kenyaUsGreenCoffeeRules.reduce((acc, rule) => {
    acc[rule.responsibleParty] = (acc[rule.responsibleParty] || 0) + 1;
    return acc;
  }, {} as Record<string, number>),
  estimatedTotalCostUsd: kenyaUsGreenCoffeeRules.reduce((sum, rule) => sum + (rule.estimatedCostUsd || 0), 0),
  estimatedMaxTimelineDays: Math.max(...kenyaUsGreenCoffeeRules.map(r => r.estimatedTimeDays || 0)),
};
